name: "${project.artifactId}"
main: "${project.groupId}.stationgates.${project.artifactId}"
version: "${project.version}"
api-version: "1.15"
author: "CoffeeAndChill"
commands:
  sg:
    description: Manage station ticket gates or validators.
    usage: /sg add/remove/cancel/mode/resolve
    permission: stationgates.sg
    permission-message: You aren't allowed to use that command
